version: '3.3'

services:
  openai-api-app:
    build: .
    image: openai-api
    container_name: openai-api
    env_file:
      - openai-api.env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - openai-api-network

  mongodb:
    image: mongo:6-jammy
    container_name: mongocontainer
    env_file:
      - mongodb.env
    volumes:
      - ./data/db:/data/db
    networks:
      - openai-api-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 5000:5000
      - 5010:5010
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - openai-api-app
    networks:
      - openai-api-network

networks:
  openai-api-network:
    driver: bridge
